### ISSUE TITLE
Webhook datetime parsing error

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [joblift/gitlab-panorama#6]
`2019-06-13 14:41:47,037 WARN  [org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver] Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Text '2019-06-13 16:36:52 +0200' could not be parsed at index 10; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Text '2019-06-13 16:36:52 +0200' could not be parsed at index 10 (through reference chain: de.joblift.service.gitlabpanorama.resources.webhook.models.WebhookEventPipeline["object_attributes"]->de.joblift.service.gitlabpanorama.gitlab.model.GitlabPipelineComplete["created_at"])]`

**Comment by stackErr-NameNotResolved** [comment]
Everytime a webhook is being executed, the error above is being thrown and the dashboard html is not updated. Seems datetime parsing does not works as expected?

**Comment by flecno** [comment]
Which gitlab version do you use? It's strange how many different datetime formats gitlab uses.

**Comment by stackErr-NameNotResolved** [comment]
11.11.0 (3e8ca2fb781)

**Comment by galan** [comment]
Hi @stackErr-NameNotResolved 
thank you for your bugreport. I retrieve the API calls in a different format, but I already recognized that the gitlab api has some glitches in their date-formats.

Just to get a better understanding when gitlab does return which format:

* Do you use the self-hosted or cloud version?
* Did you run gitlab-panorama with docker?
* Can you print the output of `timedatectl` on the machine you're running gitlab-panorama?

I extended the code to support such a format, please check if it does work now, thanks.

**Comment by stackErr-NameNotResolved** [comment]
Hey @galan,

- Self-hosted
- Yes, latest (at the time of issues creation)
- Unfortunately i can not since it is not an priority anymore...

If i do have time (allocated) in the future i will test it again so the issue can be closed. Thanks for the quick response! Sorry for not being able to test.
